services:
    mongo:
        image: mongo:5.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
        networks:
            - agenta-network
        healthcheck:
            test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 10s
            retries: 20

    mongo_express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: username
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongo
        ports:
            - "8081:8081"
        networks:
            - agenta-network
        depends_on:
            mongo:
                condition: service_healthy

networks:
    agenta-network:
        name: agenta-network

volumes:
    mongodb_data:
