docker_registry_url="registry:5001"
registry="agentaai"
database_url="sqlite:////db/deploy.db"
redis_url="redis://redis:6379/0"
docker_hub_url="http://191.168.6.44:5000/v2"
docker_registry_user="admin"
docker_registry_pass="AadminB123"
docker_registry_loc="191.168.6.44:5000"