docker_registry_url="registry:5001"
registry="agentaai"
database_url="sqlite:////db/deploy.db"
redis_url="redis://redis:6379/0"
docker_hub_url="http://127.0.0.1:5000/v2"
docker_hub_repo_owner="kedeai"
docker_hub_repo_name="agent_app"
docker_registry_user="admin"
docker_registry_pass="admin123"
docker_registry_loc="127.0.0.1:5000"